version: '3.7'

services:
  postgres-container:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: user
      POSTGRES_DB: app_db


